### PR TITLE
use align hard as target if we use aligner

### PR DESCRIPTION
**Pull request by manmay-nakhashi**

### CODE REVIEW

**Comment by manmay-nakhashi** [comment]
@lucidrains we can call Duration predictor now and expand phonemes ids as we are doing it in naturalspeech2

**Comment by lucidrains** [comment]
yes indeed, will port over the logic from NS2 Monday, and will also add the Spear-TTS text-to-semantic way of alignment

**Comment by manmay-nakhashi** [comment]
oversampled_ids = ids.repeat_interleave(durations) we just have to repeat tokens to duration output.

**Comment by lucidrains** [comment]
@manmay-nakhashi nice! i didn't know about this function 😃 🙏 

do you know if can work for batches of duration and ids?

**Comment by manmay-nakhashi** [comment]
@lucidrains i think we have to loop over or vectorize this.

**Comment by lucidrains** [comment]
no worries, i have something makeshift [here](https://github.com/lucidrains/naturalspeech2-pytorch/blob/main/naturalspeech2_pytorch/naturalspeech2_pytorch.py#L78) still need to mask out for variable lengths (durations do not all sum to the same value)

**Comment by lucidrains** [comment]
will work more on it next week

**Pull request merged**
