### PR TITLE
log mel func in torch

### PR DESCRIPTION
**Pull request by bryanhpchiang**

### CODE REVIEW

**Comment by lucidrains** [comment]
nice start!

so i was thinking, to support both mel spec w/ hifigan, as well as raw audio with soundstream / encodec, we should just make two modules, with `.encode` and `.decode` methods

then we have a simple test that just does

`module.decode(module.encode(raw_wave)) ~= raw_wave`

do you think you want to give the mel spec + hifi gan route a try?

i can get the soundstream + encodec / residual VQ stuff done by next week's end

**Comment by lucidrains** [comment]
if it is too much trouble with the difference in sampling freqs or w/e, we can just stick with the soundstream + encodec route

i think mel specs will fall out of favor anyways

**Comment by lucidrains** [comment]
Screen Shot 2023-08-06 at 10 17 08 AM

**Comment by lexkoro** [comment]
Might wanna take a look at vocos. https://github.com/charactr-platform/vocos
It supports reconstruction from Melspectrogram and encodec.

**Comment by lucidrains** [comment]
> Might wanna take a look at vocos. https://github.com/charactr-platform/vocos It supports reconstruction from Melspectrogram and encodec.

oh nice, yea, Manmay also mentioned this in the discussion; will take a look

**Comment by lucidrains** [comment]
@lexkoro @manmay-nakhashi hey, vocos looks good! i think the maintainer knows what he's doing

could you audiophiles explain why one would [decode using vocos](https://github.com/charactr-platform/vocos#reconstruct-audio-from-encodec-tokens) instead of just using the trained encodec decoder?

**Comment by manmay-nakhashi** [comment]
@lucidrains 
1. they are claiming better UTMOS and better Lstft then encodec decoder.
2. same framework can work with spectrogram and codecs.

**Comment by lucidrains** [comment]
@manmay-nakhashi thank you! btw, put up a sponsors button. i'd like to give more than just a few shallow appreciation bulletpoints :smile:

**Comment by lucidrains** [comment]
@manmay-nakhashi the truth about doing open source is that very few people can contribute meaningfully, even the ones who declare themselves this or that in their bio

**Comment by lucidrains** [comment]
ok decided to go with Encodec / Voco pair for starters

```python
import torch
from audiolm_pytorch.data import SoundDataset, get_dataloader
from voicebox_pytorch.voicebox_pytorch import EncodecVoco

ds = SoundDataset(
    '/path/to/LibriSpeech',
    target_sample_hz = 24000
)

dl = get_dataloader(ds, batch_size = 4, pad_to_longest = False)
audio, = next(iter(dl))

model = EncodecVoco()

encoded = model.encode(audio)
recon_audio = model.decode(encoded)
```

**Comment by lucidrains** [comment]
going with mel spec + vocos for now

**Pull request closed without merging**
